admit=merge(admit,PRISM3[,c("Case Index Id", "PRISM 3 Probability of Death")],all.x = TRUE, all.y = FALSE)
admit=merge(admit,PRISM3[,c("Case Index Id", "High Systolic Blood Pressure (mmHg)")],all.x = TRUE, all.y = FALSE)
admit=merge(admit,PRISM3[,c("Case Index Id", "High Systolic Blood Pressure Unknown")],all.x = TRUE, all.y = FALSE)
admit=merge(admit,PRISM3[,c("Case Index Id", "Low Systolic Blood Pressure (mmHg)")],all.x = TRUE, all.y = FALSE)
admit=merge(admit,PRISM3[,c("Case Index Id", "Low Systolic Blood Pressure Unknown")],all.x = TRUE, all.y = FALSE)
admit=merge(admit,PRISM3[,c("Case Index Id", "High Heart Rate (bpm)")],all.x = TRUE, all.y = FALSE)
admit=merge(admit,PRISM3[,c("Case Index Id", "High Heart Rate Unknown")],all.x = TRUE, all.y = FALSE)
admit=merge(admit,PRISM3[,c("Case Index Id", "Low Heart Rate (bpm)")],all.x = TRUE, all.y = FALSE)
admit=merge(admit,PRISM3[,c("Case Index Id", "Low Heart Rate Unknown")],all.x = TRUE, all.y = FALSE)